### ISSUE TITLE
Both SAS Launched Jobs (node and user) do not show activity

### ISSUE THREAD

**Issue by wweghe** [sassoftware/viya4-monitoring-kubernetes#246] opened 2021-12-07 17:36 UTC
Hi,

I just installed the latest version of the Viya 4 monitoring project, and both the SAS Launched Jobs - Node Activity and SAS Launched Jobs - User Activity, show no data, although I clearly have sas-launcher- pods running n my namespace.

Is there anything I need to configure to make sure these 2 reports work ?

The rest (CAS, Rabbitmq, postgres, ...) all show correct data)

Bye,
Wouter.

**Comment by BryanEllington** [comment] 2021-12-15 13:31
Hi Wouter,

I believe in our recent efforts to support Workload Orchestrator and update the SAS Jobs dashboards, we may have affected the display of non-SWO jobs. I believe it comes down to differences in the labels on the job pods, but I haven't investigated this fully yet.

Could you provide me with a list of the labels on a few of the jobs you are running?

**Comment by wweghe** [comment] 2021-12-17 10:48
Hi @BryanEllington ,
Here's one : 

Labels:       controller-uid=9f32e28a-d6f6-462d-bbcd-8231335d998b
              job-name=sas-launcher-c2ca0a56-37a0-4a3c-81d8-ec4f36e7bc93
              launcher.sas.com/job-type=compute-server
              launcher.sas.com/requested-by-client=sas.studio
              launcher.sas.com/username=snljro
              sas.com/created-by=sas-launcher

And this was indeed a job launched in SAS Studio, without Workload Orchestrator !

When I do the same on a system WITH Workload Orchestrator these are the labels I see : 

Labels:       app=sas-workload-orchestrator
              launcher.sas.com/job-type=compute-server
              launcher.sas.com/requested-by-client=sas.studio
              launcher.sas.com/username=sbxwvw
              sas.com/created-by=sas-launcher
              swo.sas.com/containerName=sas-programming-environment
              swo.sas.com/jobID=235
              swo.sas.com/jobName=sas-launcher-default
              swo.sas.com/queueName=default
              swo.sas.com/realm=viya401


So I guess the labels in common are : 
              launcher.sas.com/job-type=compute-server
              launcher.sas.com/requested-by-client=sas.studio
              launcher.sas.com/username=<something>
              sas.com/created-by=sas-launcher

Could this help ?
Bye,
Wouter.

**Comment by BryanEllington** [comment] 2021-12-17 12:54
Are you seeing dashboard data for jobs launched with SWO, but not without?

**Comment by wweghe** [comment] 2021-12-17 13:09
Hey Brian,

I had not yet deployed the viya4-monitoring framework in that cluster, but yes, I can confirm I can see the user activity jobs in a cluster with Workload Orchestrator :

***@***.***

***@***.***

Bye,
Wouter.

**Comment by wweghe** [comment] 2021-12-17 13:21
And by the way  :
These 2 dashboard items are also the only ones that are not "tagged" :

***@***.***

Thanks,
Wouter.

From: Wouter Van de Weghe
Sent: Friday, December 17, 2021 2:09 PM
To: sassoftware/viya4-monitoring-kubernetes ***@***.***>; sassoftware/viya4-monitoring-kubernetes ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [sassoftware/viya4-monitoring-kubernetes] Both SAS Launched Jobs (node and user) do not show activity (Issue #246)

Hey Brian,

I had not yet deployed the viya4-monitoring framework in that cluster, but yes, I can confirm I can see the user activity jobs in a cluster with Workload Orchestrator :

***@***.***

***@***.***

Bye,
Wouter.

**Comment by githje** [comment] 2022-03-04 07:42
Hi Bryan, any update to this issue? 

We're seeing the same issue in our deployment (both SAS dashboards showing job activities are empty). Our order is not using Workload Orchestrater. My suspicion is that one of the Prometheus rules is not working correctly (sas_launcher_pod_info)? 

Any hint how to fix this would be highly appreciated!

**Comment by githje** [comment] 2022-03-04 11:25
I took a closer look at the issue and hopefully found a solution. 

The issue is caused by the expression used to calculate the `sas_launcher_pod_info` rule/variable. This variable assumes that a specific metric called `sas_job_info` is available in the pushgateway to provide information about SAS jobs. However, this information will not be available if the SAS deployment does not contain the SAS Workload Orchestrator component.

A simple "solution" would be to remove this particular metric from the expression. Can you confirm that this is a suitable approach for sites without SWO? The next command patches the existing rule (it assumes that a recent version of the `yq` utility is installed):

`kubectl get prometheusrule sas-launcher-job-rules -n monitoring -o yaml | yq eval 'del(.metadata.resourceVersion, .metadata.uid, .metadata.annotations, .metadata.creationTimestamp, .metadata.selfLink, .metadata.managedFields, .status)' - | yq eval '.spec.groups[0].rules[0].expr = "sum without(container, endpoint, instance, job, service) ((label_replace(kube_pod_labels{pod=~\"sas-launcher-.+-.+-.+-.+\"}, \"job_pod\", \"$1\", \"pod\", \"(.+)\")) * on(pod) group_left(node) kube_pod_info{pod=~\"sas-launcher-.+-.+-.+-.+\"})"' - | kubectl apply -f -`

**Comment by BryanEllington** [comment] 2022-03-08 13:46
`sas_job_info` is provided by SWO. It looks like:

```none
# HELP sas_job_info Information on pending and running SAS jobs
# TYPE sas_job_info gauge
sas_job_info{job_name="my-job",queue_name="default",job_pod="sas-launcher-wxyz-abcd-abcd-6789"} 1
```
 The dashboards have job name and queue filters. I'm not sure they will display jobs without those fields. Having "friendly" job and queue names helps users filter the jobs. Using labels directly from `kube_pod_labels` had issues because of the tight character restrictions for Kubernetes label values.  The other purpose of `sas_job_info` was to reduce inaccuracies in the jobs dashboards from "joining" too many other metrics collected from different sources causing some panel values to out of sync with others.

We know we have an issue here but just haven't settled on the right fix to handle both SWO and non-SWO jobs consistently while still supporting the requirement job and queue names and the special characters they can contain.

We've also avoiding imposing additional dependencies on the user environment like `yq`. We're going to be moving to a containerization model that will address this and give the scripts access to whatever utilities or programs (like Python scripts) might be needed.

I wish I had a better answer, but it is something we're looking at and hope to address soon.

**Comment by DoritozX** [comment] 2022-09-07 03:57
Hi @BryanEllington , we are having the same problem and I would like to confirm that at the moment if we want to use the two dashboards, is it assumed that this requires the purchase of a SAS Workload Orchestrater license? Thank you!

**Comment by gsmith-sas** [comment] 2022-09-14 14:30
@DoritozX @wweghe These dashboards only report on SAS Workload Orchestrator jobs, so a SWO license is required.  Support for non-SWO jobs is on our list of future enhancements but we don't have a timeline for when we will deliver it.  We have updated the Grafana dashboards to include tags indicating these dashboards are SAS Viya related and also to indicate they are related to SWO.  I think that covers the open questions so I'm going to close this issue.  Regards.

**Closed by gsmith-sas** 2022-09-14 14:30 UTC
