### ISSUE TITLE
failed calling webhook validate.nginx.ingress.kubernetes.io

### ISSUE THREAD

**Issue by mauriziopinzi** [sassoftware/viya4-monitoring-kubernetes#319] opened 2022-03-28 12:46 UTC
I got this issue when I tried to install the monitoring on AKS 1.22 (it may be rilevant)

W0328 10:52:45.748943    6465 reflector.go:441] k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Error: release v4m-prometheus-operator failed, and has been uninstalled due to atomic being set: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.0.144.68:443: connect: connection refused
ERROR Exiting script [deploy_monitoring_cluster.sh] due to an error executing the command [helm $helmDebug upgrade --install $promRelease --namespace $MON_NS -f monitoring/values-prom-operator.yaml -f $istioValuesFile -f $tlsValuesFile -f $nodePortValuesFile -f $wnpValuesFile -f $PROM_OPER_USER_YAML --atomic --timeout 20m --set nameOverride=$promName --set fullnameOverride=$promName --set prometheus-node-exporter.fullnameOverride=$promName-node-exporter --set kube-state-metrics.fullnameOverride=$promName-kube-state-metrics --set grafana.fullnameOverride=$promName-grafana --set grafana.adminPassword="$grafanaPwd" --version $KUBE_PROM_STACK_CHART_VERSION prometheus-community/kube-prometheus-stack].

**Comment by gsmith-sas** [comment] 2022-03-28 17:38
@mauriziopinzi   I do not believe we have seen the error you reported before.   And I just successfully deployed this project's monitoring stack (including Prometheus and Grafana) onto an Azure (AKS) cluster running Kubernetes 1.22.4.    This leads me to believe the problem you encountered was likely caused by a temporary network issue or, possibly, a mistake in your configuration.  I suggest you try it again.  If the problem happens repeatedly, please confirm that your nginx configuration is correct and review the nginx log for errors or messages.  Please let us know how it goes.

**Comment by mauriziopinzi** [comment] 2022-03-29 09:13
Indeed I did another test and I'm able to install it, you can close the issue

**Comment by gsmith-sas** [comment] 2022-03-29 12:43
I am glad to hear that you were able to get things working.  Closing the issue.

**Closed by gsmith-sas** 2022-03-29 12:43 UTC
