### ISSUE TITLE
Helm 3.9 compatibility issue

### ISSUE THREAD

**Issue by nallagangus** [sassoftware/viya4-monitoring-kubernetes#368] opened 2022-06-22 17:48 UTC
Helm version 3.9.0 (latest as of  June 2022) causes an error dring kibana logging install.

“Error: Kubernetes cluster unreachable: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1”.

Once we downgraded HELM to 3.8.2 we are able to successfully install Kibana/logging.

Please put in above note "Dependencies - Helm version" 

Sudhir

**Comment by gsmith-sas** [comment] 2022-06-22 20:07
@nallagangus Hmmm, I just downloaded Helm 3.9.0 onto a machine and did not have any problems deploying the log monitoring components.  I'm wondering if the problem is really tied to the version of Kubernetes you were using.  Or, if it a cloud provider-related issue: a Google search for the error turns up several postings reporting that AWS had a problem (now fixed) with Helm 3.9.0.  

- What version of Kubernetes are you using?  
- And is your cluster located on an external cloud-provider?  If so, which one?  
- Are you running our deployment script manually or are using some form of automation (such as the Viya 4 Deployment project)?

Thanks!

**Comment by nallagangus** [comment] 2022-06-22 21:25
It is on AWS

k8s 1.20.0 on EKS

viya4 deployment project github  (Viya4 is deployed separately using
operator and that does no have issues)

**Closed** 2022-06-22 23:00 UTC

**Comment by gsmith-sas** [comment] 2022-06-23 17:57
@govind-bt   In the AWS Issue I provided a link for above, the user nathan100b posted (on 20JUN22) a solution that worked for him.  You may want to try that.  However, as this appears to be an AWS issue and I am not an AWS expert, I can't speak to whether it is the "right" solution.
