### ISSUE TITLE
Grafana username "admin" and password not working

### ISSUE THREAD

**Issue by irchum** [sassoftware/viya4-monitoring-kubernetes#354] opened 2022-06-03 09:42 UTC
Hi All,
I'm Ira from SAS Technical Support. I'm working on a ticket opened by a PSD engineer following Viya 2021.2.5 deployment on AWS.
Viya Monitoring has been installed with the project [Viya 4 Deployment ](https://github.com/sassoftware/viya4-monitoring-kubernetes). He configured the password in the ansible-vars.yaml file with the variable [V4M_GRAFANA_PASSWORD](https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md#monitoring-and-logging).

In the Ansible installation log, the following message appears:
TASK [monitoring : cluster-monitoring - output credentials] ********************
ok: [localhost] => {
    "msg": [
        "Grafana - username: admin, password: Password123"
    ]
}

When he logs in to Grafana, he gets an error: invalid username or password. He also tried admin/admin but it doesn't work.

I've asked him to check the current password, which is kept as a pod secret, by querying the info using Kubectl. He tried it, but the issue is still persisting:

kubectl -n monitoring get secret v4m-grafana -o yaml 
apiVersion: v1
data:
  admin-password: UGFzc3dvcmQxMjM=
  admin-user: YWRtaW4=

echo "YWRtaW4=" | base64 --decode
admin
echo "UGFzc3dvcmQxMjM=" | base64 --decode
Password123
------------
Is there any additional steps to be performed while setting up Grafana by using this project?

Thank you for your help

Best regards,
Ira

**Comment by gsmith-sas** [comment] 2022-06-03 14:19
@irchum I think there may be two separate issues here.  First, the it appears that the Viya 4 Deployment project did not honor/use the password the user provided.  That issue will have to be addressed by the Viya 4 Deployment project team.  I would suggest you open an (separate) issue with that team directly.  

Second, it appears that the password stored in the v4m-grafana secret is not correct.  That does appear to be a problem on this project.  Or, possibly with the prometheus-operator we use to deploy Grafana.  In any case, I have confirmed that if you change the Grafana password the secret is _not_ updated.  That is a bug and we will address it in a future release.  In the meantime, users will need to manually update the v4m-grafa secret after they change Grafana password.  Instructions for how to change the Grafana password are included in the [ACCESS MONITORING APPLICATIONS](https://github.com/sassoftware/viya4-monitoring-kubernetes/tree/master/monitoring#access-monitoring-applications) section of the monitoring/README.md file in this repo.  After following the instructions there for changing the password, the user can manually update (using a tool like Lens, perhaps) the admin-password data item in v4m-grafana secret can be updated with the new password.

**Comment by irchum** [comment] 2022-06-07 12:18
@gsmith-sas Thank you for your feedback. I have asked the user to manually update v4m-grafa secret. He did it but the behavior is still the same. He performed the following:
- Updated the v4m-grafana secret via kubectl
- Reset the password with grafana-cli admin reset-admin-password.
- Restarted the pod

**Comment by gsmith-sas** [comment] 2022-06-14 20:23
@irchum I apologize for the delayed response, I was out of the office.

I have confirmed that after following the following steps I can a) log into Grafana with the new password; and, b) the secret contains the new password.  I have also confirmed that I can still access Grafana with the new password after restarting the Grafana pod.

```
-bash-4.2$ kubectl exec -n monitoring v4m-grafana-579bd99797-95cnd -c grafana -- bin/grafana-cli admin reset-admin-password password
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Starting Grafana" version= commit= branch= compiled=1970-01-01T00:00:00Z
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations"
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled."
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana/"
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_USER=admin"
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_PASSWORD=*********"
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Path Data" path=/var/lib/grafana/
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2022-06-14T20:06:46.18+0000 lvl=info msg="App mode production"
logger=sqlstore t=2022-06-14T20:06:46.18+0000 lvl=info msg="Connecting to DB" dbtype=sqlite3
logger=migrator t=2022-06-14T20:06:46.25+0000 lvl=info msg="Starting DB migrations"
logger=migrator t=2022-06-14T20:06:46.27+0000 lvl=info msg="migrations completed" performed=0 skipped=381 duration=1.027581ms

Admin password changed successfully ✔

-bash-4.2$ echo Grafana User: $(kubectl -n monitoring get secret v4m-grafana -o=jsonpath={.data.admin-user} | base64 -d)
Grafana User: admin
-bash-4.2$ echo Grafana Password: $(kubectl -n monitoring get secret v4m-grafana -o=jsonpath={.data.admin-password} | base64 -d)
Grafana Password: admin
-bash-4.2$
-bash-4.2$ echo password|base64
cGFzc3dvcmQK
-bash-4.2$ kubectl -n monitoring patch secret v4m-grafana --type='json' -p='[{"op" : "replace" ,"path" : "/data/admin-password" ,"value" : "cGFzc3dvcmQK"}]'
secret/v4m-grafana patched
-bash-4.2$ echo Grafana User: $(kubectl -n monitoring get secret v4m-grafana -o=jsonpath={.data.admin-password} | base64 -d)
Grafana User: password
```
I am not sure why your customer ran into problems.  Please ask them to follow the steps (as shown above) and confirm the problem persists.

**Comment by gsmith-sas** [comment] 2022-06-15 13:43
@irchum Hmmm, given all of the messages indicating success, it is very strange that the problem persists.  How is the problem presenting itself?  When the user attempts to log into Grafana with the updated credentials, is Grafana displaying error messages indicating that the password is invalid?  After removing and reinstalling the monitoring tools, why was the password changed?  Was that just to verify the password change process?

**Comment by irchum** [comment] 2022-06-16 12:56
@gsmith-sas password changed to verify if it works with the updated password. The engineer confirmed that there is only one instance of Grafana. he works on the same environment (Viya 2021.2.5 deployed on AWS). SAS Viya 4 team was't able to create the issue the enginner has. They also see some different behavior regarding the logging of errors and informational messages when they access Grafana. Viya 4 team has proposed a team session with the engineer to see the installation etc.

**Comment by Andy-Tr** [comment] 2022-06-16 17:55
We found that another grafana installation was using the same DNS name grafana.<domain_name> as the instance installed by viya4 deployment.  The customer updated V4M_GRAFANA_FQDN to be viyagrafana.<domain_name> and was able to successfully log in to the viya4 deployment instance.

**Comment by gsmith-sas** [comment] 2022-06-16 19:02
Thanks for the update @Andy-Tr.  I'm glad the problem was resolved.

**Closed by gsmith-sas** 2022-06-16 19:02 UTC
